name: CI - Train Titanic Model

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci.yml'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install pandas>=1.3.0 scikit-learn>=1.0 mlflow>=2.0 joblib>=1.2.0

      - name: Run MLflow Project
        working-directory: ./MLProject   # ✅ Lebih stabil daripada `cd`
        run: |
          mlflow run . --env-manager=local

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4  # ✅ v4 untuk menghindari error deprecated
        with:
          name: trained-model
          path: MLProject/artifacts/model.pkl
